
version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "rehype-highlight"
      - dependency-name: "rehype-rehype"
      - dependency-name: "remark-gfm"
      - dependency-name: "remark-slug"
      - dependency-name: "remark-slug"