
version: 2
updates:
  - package-ecosystem: "yarn" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react*"
        versions: ["17.x"]
