
version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
        versions: ["17.x"]
      - dependency-name: "react-dom"
        versions: ["17.x"]
