name: "Dependabot Automerge - Action"
on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
