name: Main
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build & Lint"
    runs-on: ubuntu-latest
    if: ${{ github.actor !== 'dependabot[bot]' }}
    environment: production
    strategy:
      matrix:
        node: ["12.16"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Lint & Build
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          rm -f .yarnclean
          yarn --frozen-lockfile
          yarn lint
          yarn build
